# Netlify Configuration File
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # No build command needed - static site
  command = ""
  # Publish directory (root of the repository)
  publish = "."
  # Functions directory
  functions = "netlify/functions"

# Redirect rules for single page app behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variable placeholder
# Add your GEMINI_API_KEY in Netlify dashboard:
# Site settings → Environment variables → Add variable
# Key: GEMINI_API_KEY
# Value: Your Gemini API key
